// This file is part of DM-HEOM (https://github.com/noma/dm-heom)
//
// Copyright (c) 2015-2019 Matthias Noack, Zuse Institute Berlin
// Copyright (c) 2016-2017 Lucas Deecke, Zuse Institute Berlin
//
// Licensed under the 3-clause BSD License, see accompanying LICENSE,
// CONTRIBUTORS.md, and README.md for further information.

#include "heom/hierarchy_arithmetic_scale.hpp"

namespace heom {

const std::string hierarchy_arithmetic_scale::embedded_ocl_source_ {
#include "hierarchy_arithmetic_scale.cl.hpp"  // NOTE: generated by CMake
};
const std::string hierarchy_arithmetic_scale::embedded_ocl_kernel_name_ { "hierarchy_arithmetic_scale" };

hierarchy_arithmetic_scale::hierarchy_arithmetic_scale(ocl::helper& ocl, const std::string& source_header, const std::string& ocl_compile_options, const ocl::nd_range& range)
	: ocl::kernel_wrapper(ocl, embedded_ocl_source_, embedded_ocl_kernel_name_, source_header, ocl_compile_options, range)
{
}

hierarchy_arithmetic_scale::hierarchy_arithmetic_scale(ocl::helper& ocl, const boost::filesystem::path& hierarchy_arithmetic_scale_file_name, const std::string& hierarchy_arithmetic_scale_kernel_name, const std::string& source_header, const std::string& ocl_compile_options, const ocl::nd_range& range)
	: ocl::kernel_wrapper(ocl, hierarchy_arithmetic_scale_file_name, hierarchy_arithmetic_scale_kernel_name, source_header, ocl_compile_options, range)
{
}

void hierarchy_arithmetic_scale::run(cl::Buffer& d_mem_a, complex_t b, cl::Buffer& d_mem_dst)
{
	cl_int err = 0;

	// set dynamic kernel arguments
	err = kernel_.setArg(0, d_mem_a);
	ocl::error_handler(err, "clSetKernelArg(0)");
	err = kernel_.setArg(1, b);
	ocl::error_handler(err, "clSetKernelArg(1)");
	err = kernel_.setArg(2, d_mem_dst);
	ocl::error_handler(err, "clSetKernelArg(2)");

	run_kernel();
}


} // namespace heom
