// This file is part of DM-HEOM (https://github.com/noma/dm-heom)
//
// Copyright (c) 2015-2019 Matthias Noack, Zuse Institute Berlin
//
// Licensed under the 3-clause BSD License, see accompanying LICENSE,
// CONTRIBUTORS.md, and README.md for further information.

#include "heom/rk_weighted_add.hpp"

namespace heom {

const std::string rk_weighted_add_ocl_source {
#include "rk_weighted_add.cl.hpp"  // NOTE: generated by CMake
};
const std::string rk_weighted_add_ocl_kernel_name { "rk_weighted_add" };

} // namespace heom
